apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-pv-1
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce # 데이터 무결성을 위해 하나의 노드에서만 쓰기가능
  persistentVolumeReclaimPolicy: Retain # 데이터 보존용
  storageClassName: zookeeper-data #volumeclaim에 이름 매치
  nfs:
    server: 172.16.30.5
    path: /volume1/cloud_data/zookeeper1 #nfs 서버에 용량 마운트할 경로
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-pv-2
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: zookeeper-data
  nfs:
    server: 172.16.30.5
    path: /volume1/cloud_data/zookeeper2 
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-pv-3
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: zookeeper-data
  nfs:
    server: 172.16.30.5
    path: /volume1/cloud_data/zookeeper3  