apiVersion: v1
kind: PersistentVolume
metadata:
  name: solr-pv-1
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: solr-data
  nfs:
    server: 172.16.30.5
    path: /volume1/cloud_data/solrcloud1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: solr-pv-2
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: solr-data
  nfs:
    server: 172.16.30.5
    path: /volume1/cloud_data/solrcloud2